import type { BuyerFrame, Fixture, Planogram, Product } from './types';
import type { Locale } from './i18n';
import type { BrandKit } from './brand-kit';

/**
 * Builds a native .pptx (4 slides: title, space plan, planogram, buyer deck)
 * entirely in the browser via pptxgenjs (dynamic import keeps it out of the
 * main bundle). No data leaves the client.
 */

const NAVY = '10163A';
const MUTED = '64748B';
const BORDER = 'E3E7F0';

const L = {
  fr: {
    subtitle: 'Recommandation catégorie générée par CatPilot',
    strategy: 'Stratégie',
    shelves: (s: number, f: number) => `${s} niveaux · ${f} facings/niveau`,
    masse: 'Plan de masse',
    thead: ['Marque', 'Réf.', 'Facings', '% linéaire', '% CA', 'Écart'],
    plano: 'Planogramme au facing',
    trame: 'Trame de présentation acheteur',
    moves: 'Moves clés',
    novelties: 'Nouveautés',
    impact: 'Impact attendu',
    footer: 'Généré avec CatPilot',
    enseigne: 'Enseigne',
    category: 'Catégorie',
  },
  en: {
    subtitle: 'Category recommendation generated by CatPilot',
    strategy: 'Strategy',
    shelves: (s: number, f: number) => `${s} shelves · ${f} facings/shelf`,
    masse: 'Space plan',
    thead: ['Brand', 'SKUs', 'Facings', '% of shelf', '% of value', 'Gap'],
    plano: 'Facing-level planogram',
    trame: 'Buyer presentation deck',
    moves: 'Key moves',
    novelties: 'New products',
    impact: 'Expected impact',
    footer: 'Generated with CatPilot',
    enseigne: 'Retailer',
    category: 'Category',
  },
};

function hex(color: string): string {
  return color.replace('#', '').toUpperCase();
}

function pct(x: number): string {
  return `${Math.round(x * 100)}%`;
}

export async function exportPptx(opts: {
  plano: Planogram;
  products: Product[];
  fileName: string;
  strategyLabel: string;
  fixture: Fixture;
  locale: Locale;
  /** Trame éditée par l'utilisateur (sinon la trame générée). */
  frame?: BuyerFrame;
  /** Charte de marque (couleurs + logo + nom) appliquée au deck. */
  kit?: BrandKit | null;
  /** Enseigne cible du plan (fichier multi-enseigne) — nommée sur le deck. */
  enseigne?: string | null;
  /** Catégorie analysée (fichier multi-catégorie). */
  category?: string | null;
}): Promise<void> {
  const { plano, fileName, strategyLabel, fixture, locale, kit } = opts;
  const enseigne = opts.enseigne?.trim() || '';
  const category = opts.category?.trim() || '';
  const t = L[locale];
  const accent = kit?.colors?.primary ? hex(kit.colors.primary) : NAVY;
  const darkBg = kit?.colors?.dark ? hex(kit.colors.dark) : NAVY;
  const company = kit?.company?.trim() || '';
  const logo = kit?.logoData || null;
  const PptxGenJS = (await import('pptxgenjs')).default;
  const pptx = new PptxGenJS();
  pptx.defineLayout({ name: 'WIDE', width: 10, height: 5.625 });
  pptx.layout = 'WIDE';

  const dateStr = new Date().toLocaleDateString(locale === 'fr' ? 'fr-FR' : 'en-GB');

  /* ---- Slide 1 : titre ---- */
  const s1 = pptx.addSlide();
  s1.background = { color: darkBg };
  s1.addText(company || 'CatPilot', { x: 0.6, y: 0.55, w: 7.0, h: 0.5, fontSize: 20, bold: true, color: 'FFFFFF' });
  if (logo) {
    s1.addImage({ data: logo, x: 8.0, y: 0.4, w: 1.4, h: 0.8, sizing: { type: 'contain', w: 1.4, h: 0.8 } });
  }
  s1.addText(fileName || 'Category review', {
    x: 0.6, y: 1.9, w: 8.8, h: 1.1, fontSize: 34, bold: true, color: 'FFFFFF',
  });
  s1.addText(t.subtitle, { x: 0.6, y: 3.0, w: 8.8, h: 0.4, fontSize: 14, color: 'C7CBE6' });
  // Périmètre : enseigne cible + catégorie (fichiers multi-enseigne/multi-catégorie).
  const scope = [enseigne && `${t.enseigne} : ${enseigne}`, category && `${t.category} : ${category}`]
    .filter(Boolean).join('     ·     ');
  if (scope) {
    s1.addText(scope, { x: 0.6, y: 3.5, w: 8.8, h: 0.4, fontSize: 13, bold: true, color: 'FFFFFF' });
  }
  s1.addText(
    `${t.strategy} : ${strategyLabel}   ·   ${t.shelves(fixture.shelves, fixture.facingsPerShelf)}   ·   ${dateStr}`,
    { x: 0.6, y: 4.6, w: 8.8, h: 0.4, fontSize: 12, color: 'C7CBE6' }
  );

  /* ---- Slide 2 : plan de masse ---- */
  const s2 = pptx.addSlide();
  s2.addText(t.masse, { x: 0.5, y: 0.3, w: 9, h: 0.5, fontSize: 20, bold: true, color: accent });
  if (scope) s2.addText(scope, { x: 0.5, y: 0.66, w: 8.2, h: 0.22, fontSize: 10, color: MUTED });
  if (logo) s2.addImage({ data: logo, x: 8.9, y: 0.25, w: 0.6, h: 0.35, sizing: { type: 'contain', w: 0.6, h: 0.35 } });

  // Stacked shelf-share bar
  let bx = 0.5;
  for (const b of plano.brandBlocks) {
    const w = Math.max(0.05, b.share * 9);
    s2.addShape(pptx.ShapeType.rect, { x: bx, y: 0.95, w, h: 0.42, fill: { color: hex(b.color) }, line: { color: 'FFFFFF', width: 0.5 } });
    if (b.share > 0.09) {
      s2.addText(b.brand, { x: bx, y: 0.95, w, h: 0.42, fontSize: 9, bold: true, color: 'FFFFFF', align: 'center', valign: 'middle' });
    }
    bx += w;
  }

  const rows: unknown[] = [
    t.thead.map((h) => ({ text: h, options: { bold: true, color: MUTED, fontSize: 10 } })),
  ];
  for (const b of plano.brandBlocks) {
    const gap = Math.round((b.share - b.revenueShare) * 100);
    rows.push([
      { text: b.brand, options: { fontSize: 10, bold: true } },
      { text: String(b.products), options: { fontSize: 10 } },
      { text: String(b.facings), options: { fontSize: 10 } },
      { text: pct(b.share), options: { fontSize: 10 } },
      { text: pct(b.revenueShare), options: { fontSize: 10 } },
      { text: `${gap > 0 ? '+' : ''}${gap} pts`, options: { fontSize: 10, color: gap > 3 ? 'B45309' : gap < -3 ? '2B3FF5' : MUTED } },
    ]);
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  s2.addTable(rows as any, {
    x: 0.5, y: 1.65, w: 9,
    colW: [2.6, 1.0, 1.3, 1.4, 1.4, 1.3],
    border: { type: 'solid', color: BORDER, pt: 0.5 },
    align: 'left', valign: 'middle', rowH: 0.28,
  });

  /* ---- Slide 3 : planogramme ---- */
  const s3 = pptx.addSlide();
  s3.addText(t.plano, { x: 0.5, y: 0.3, w: 9, h: 0.5, fontSize: 20, bold: true, color: accent });
  if (logo) s3.addImage({ data: logo, x: 8.9, y: 0.25, w: 0.6, h: 0.35, sizing: { type: 'contain', w: 0.6, h: 0.35 } });

  const areaY = 1.0;
  const areaH = 3.7;
  const n = plano.shelves.length || 1;
  const rowH = Math.min(0.75, areaH / n);
  const labelW = 1.5;
  const cellsX = 0.5 + labelW + 0.1;
  const cellsW = 9 - labelW - 0.1;

  plano.shelves.forEach((shelf, i) => {
    const y = areaY + i * (areaH / n);
    s3.addText(shelf.label, { x: 0.5, y, w: labelW, h: rowH, fontSize: 9, color: MUTED, valign: 'middle' });
    // shelf base line
    s3.addShape(pptx.ShapeType.rect, { x: cellsX, y: y + rowH - 0.03, w: cellsW, h: 0.03, fill: { color: 'D6CCC0' } });
    let cx = cellsX;
    for (const cell of shelf.cells) {
      const w = Math.max(0.12, (cell.facings / fixture.facingsPerShelf) * cellsW - 0.02);
      const block = plano.brandBlocks.find((b) => b.brand === cell.product.brand);
      s3.addShape(pptx.ShapeType.rect, {
        x: cx, y: y + 0.04, w, h: rowH - 0.12,
        fill: { color: hex(block?.color || '94A3B8') },
        line: { color: 'FFFFFF', width: 0.75 },
      });
      if (w > 0.85) {
        s3.addText(`${cell.product.name}${cell.product.isNew ? '  · NEW' : ''}`, {
          x: cx + 0.03, y: y + 0.04, w: w - 0.06, h: rowH - 0.12,
          fontSize: 7, color: 'FFFFFF', valign: 'middle', shrinkText: true,
        });
      }
      cx += w + 0.02;
    }
  });

  // Legend
  let lx = 0.5;
  const ly = areaY + areaH + 0.15;
  for (const b of plano.brandBlocks.slice(0, 8)) {
    s3.addShape(pptx.ShapeType.rect, { x: lx, y: ly + 0.04, w: 0.16, h: 0.16, fill: { color: hex(b.color) } });
    const tw = Math.min(1.6, 0.25 + b.brand.length * 0.085);
    s3.addText(b.brand, { x: lx + 0.2, y: ly, w: tw, h: 0.25, fontSize: 9, color: MUTED, valign: 'middle' });
    lx += 0.25 + tw;
  }

  /* ---- Slide 4 : trame acheteur ---- */
  const s4 = pptx.addSlide();
  const f = opts.frame ?? plano.buyerFrame;
  s4.addText(t.trame, { x: 0.5, y: 0.3, w: 9, h: 0.4, fontSize: 20, bold: true, color: accent });
  if (logo) s4.addImage({ data: logo, x: 8.9, y: 0.25, w: 0.6, h: 0.35, sizing: { type: 'contain', w: 0.6, h: 0.35 } });
  s4.addText(f.headline, { x: 0.5, y: 0.85, w: 9, h: 0.4, fontSize: 14, bold: true, color: '0F172A' });
  s4.addText(f.categorySummary, { x: 0.5, y: 1.3, w: 9, h: 0.6, fontSize: 10, color: '475569' });

  const cols: [string, string[]][] = [
    [t.moves, f.keyMoves],
    [t.novelties, f.noveltyPitch],
    [t.impact, f.expectedImpact],
  ];
  cols.forEach(([title, items], i) => {
    const x = 0.5 + i * 3.1;
    s4.addText(title.toUpperCase(), { x, y: 2.05, w: 2.9, h: 0.3, fontSize: 10, bold: true, color: MUTED, charSpacing: 2 });
    s4.addText(
      items.map((txt) => ({ text: txt, options: { bullet: { characterCode: '2014', indent: 12 }, fontSize: 9.5, color: '475569', paraSpaceAfter: 6 } })),
      { x, y: 2.4, w: 2.9, h: 2.9, valign: 'top' }
    );
  });
  s4.addText(`${company ? company + ' · ' : ''}${t.footer} · ${dateStr}`, { x: 0.5, y: 5.25, w: 9, h: 0.3, fontSize: 8, color: MUTED });

  const safe = (fileName || 'catpilot').replace(/\.[^.]+$/, '').replace(/[^\w\dÀ-ÿ -]+/g, '_').slice(0, 60);
  await pptx.writeFile({ fileName: `CatPilot — ${safe}.pptx` });
}
